### ISSUE TITLE
Scroll animation starts midway on page load.

### ISSUE THREAD

**Issue by Samushel** [homerjam/angular-scroll-magic#11]
Hello, I'm having this weird behavior when setting a scrolling Tween. My setup uses out of the box functionality and I haven't modified anything inside my controllers. 

When the page first loads, the effect (be it changing position or rotating it) is setup like it was already in the middle of the scrolling event. In my case the transform matrix starts like this: 

`matrix(0.89632, 0.44338, -0.44338, 0.89632, 0, 0)`

If I scroll down and finish the animation and scroll back up the matrix looks like it should from the beginning:

`matrix(1, 0, 0, 1, 0, 0)`

My HTML markup looks like this: 

```html
<div class="chevron_down">
  <a sm-tween="projects"
     to-vars="{rotation: '180'}"
     ng-href="#home-projects">
    Go
  </a>
</div>

<div sm-scene="projects" duration="300" offset="0" trigger-hook="1"></div>

<div class="project-grid" id="home-projects">
  <h2>Projects</h2>
  <p class="wide-legend">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore.
  </p>
</div>
```
Angular version: 1.5.8
Scrollmagic version: 2.0.5
Angular Scroll Magic version: 0.0.9

Tested on browers:
Chrome: 54.0.2840.87
Firefox: 49.0.2
Microsoft Edge: 39.14931

**Comment by homerjam** [comment]
Hi there

The only thing I can think of is perhaps the scene trigger element (`sm-scene` by default) is pushed down the viewport by the preceding element causing the scene to begin beyond the desired start point. You could try absolutely positioning the elements perhaps to test this.

Failing that please update `angular-scroll-magic` and create a plunkr/fiddle/codepen example so we can debug more easily.

Thanks

**Comment by Samushel** [comment]
Thanks for the quick response. I tried changing the positions around and making everything with fixed heights for example, but still got the same result.

Here is the plunker with a basic example of what I'm trying to do that replicates the issue: https://plnkr.co/b8A3gJyXcPuNuY5m9zy3

**Comment by homerjam** [comment]
Hi @Samushel 

I found the problem - the initialisation of the scene is delayed to allow for any `ng-repeat`s to finish, this delay allowed the tween to begin running as it was initialised immediately. I've now made the tweens initialise on creation of the scene. This may have a side effect of delaying any `fromVars` but will have to wait to determine this based on further use cases.

**Comment by Samushel** [comment]
Thank you very much for your help. Working for me now!
