### ISSUE TITLE
Allow tweens to trigger TimelineMax objects

### ISSUE THREAD

**Issue by zurie** [homerjam/angular-scroll-magic#3]
The power of scrollmagic is the ability to allow complex tweens through the use of timelines.  It would be nice if it was possible to call a timeline from sm-tween.  Without the ability to run a timeline, its not possible to animate multiple objects (think UL > LI > a) where you want to change the LI and the A based on the same scroll position or complex parallax animations.

**Comment by homerjam** [comment]
Thanks for bringing this up - the directive is in its infancy still so very useful feedback.

What would really help me understand the problem is an example of how you would do this without angular, as god intended so to speak. Is there already an example on the Scrollmagic site? Or if not could you possibly create a plunkr/fiddle/codepen?

**Comment by zurie** [comment]
var mytween = new TimelineMax()
   .to(".centered-navigation", 0.5, {backgroundColor: "#E8E9E8"}) // trigger a TweenMax.to tween
   .to(".mobile-logo span", 0.5, {color: "black"}, "-=.5")
   .to(".centered-navigation ul li.nav-link a", 0.5, {color: "black"}, "-=.5")
   .to(".centered-navigation .nav-link", 0.5, {color: "rgba(255,255,255,.7)"}, "-=.5")
   .to("ul.submenu li a", 0.5, {color: "black" }, "-=.5")
   .to("ul.submenu li a", 0.5, {backgroundColor: "#E8E9E8" }, "-=.5")

var scene = new ScrollMagic.Scene({
   triggerElement: "#home-section",triggerHook: "onEnter",duration: "75%"})
   .setTween(mytween)
   .addTo(controller);

Obviously this tween doesn’t have any relevance to you without a working example, but the basic concept is that you would setTween as a variable, and that said variable is a TimeLineMax() object.

there is also a example on the website. (click view source to see the example).

http://scrollmagic.io/examples/advanced/advanced_tweening.html http://scrollmagic.io/examples/advanced/advanced_tweening.html

**Comment by homerjam** [comment]
I think you could achieve this without any changes to the directive. Its simply a case of approaching it in a different way to how you'd typically go about it.

Internally the directive adds `sm-tween`s to a timeline which is added to a scene. So in this scenario you would just add the `sm-tween` directive to each element (`.centered-navigation`, `.mobile-logo` etc) you that you want to include in the timeline with the corresponding css/vars.

**Comment by zurie** [comment]
But with a timelinemax object I can  do callbacks to variables and use stagger and onComplete functions.  How would we approach those circumstances.  If we had the ability to call a object as our tween we could do anything we wanted inside javascript rather than forcing it into the directive’s data attributes.  Thoughts?

```

<script>
    // define images
    var images = [
        "../../img/example_imagesequence_01.png",
        "../../img/example_imagesequence_02.png",
        "../../img/example_imagesequence_03.png",
        "../../img/example_imagesequence_04.png",
        "../../img/example_imagesequence_05.png",
        "../../img/example_imagesequence_06.png",
        "../../img/example_imagesequence_07.png"
    ];

    // TweenMax can tween any property of any object. We use this object to cycle through the array
    var obj = {curImg: 0};

    // create tween
    var tween = TweenMax.to(obj, 0.5,
        {
            curImg: images.length - 1,  // animate propery curImg to number of images
            roundProps: "curImg",               // only integers so it can be used as an array index
            repeat: 3,                                  // repeat 3 times
            immediateRender: true,          // load first image automatically
            ease: Linear.easeNone,          // show every image the same ammount of time
            onUpdate: function () {
              $("#myimg").attr("src", images[obj.curImg]); // set the image source
            }
        }
    );

    // init controller
    var controller = new ScrollMagic.Controller();

    // build scene
    var scene = new ScrollMagic.Scene({triggerElement: "#trigger", duration: 300})
                    .setTween(tween)
                    .addIndicators() // add indicators (requires plugin)
                    .addTo(controller);

    // handle form change
    $("form.move input[name=duration]:radio").change(function () {
        scene.duration($(this).val());
    });
</script>
```

**Comment by homerjam** [comment]
You can pass a scope object to the `sm-tween`'s `vars` attribute - this allows you to define css and callbacks (onComplete, onUpdate etc) in js (in your controller for example).

You can also access scenes in js using the `ScrollMagicService` - just call `ScrollMagicService.getScene(sceneId)`. Thus allowing you to change duration etc.

Although it feels like you're being forced to go about this the long way around by using data attributes this is "the angular way" - defining things in the markup. It makes it much easier to then reuse components between projects.

**Comment by zurie** [comment]
ok thanks! I think i understand.  I was able to do some onComplete events and other things.  If you ever get around to it, it would be nice to throw some more complex examples on the demo page to illustrate some of the more advanced controller scene logic.  Thanks!

**Comment by homerjam** [comment]
Agreed! Will definitely try and improve. Appreciate the feedback
