### ISSUE TITLE
triggerElement not recognizing id element of an expression

### ISSUE THREAD

**Issue by techno-mike-git** [homerjam/angular-scroll-magic#6]
Hi, I was wondering if you could help me out on tween2. I'm doing a ng-repeat and trying to define the triggerElement with an id but it's not recognizing the element. 

> (ScrollMagic.Scene) -> ERROR: Element defined in option "triggerElement" was not found: #time-free

Here's the sample code of my ng-repeat: 

`<li class="timeline__left" ng-repeat="line in lines">
          <div class="timeline__badge badge--{{line.id}}" sm-scene="tween-{{line.id}}" trigger-element="'#time-{{line.id}}'" duration="40%" offset="-100">
          </div>
          <div id="time-{{line.id}}" class="timeline__panel" sm-tween="tween-{{line.id}}" from-vars="{right: '120%'}" to-vars="vm.toVars">
            <div class="timeline__panel--heading">
              <h4>{{line.title}}</h4>
              <h3>{{line.company}}</h3>
              <small>{{line.from}} - {{line.to}}</small>
            </div>
            <div class="timeline__body">
              <p>{{line.detail}}</p>
            </div>
          </div>
        </li>`

Any help will be great. Thanks

**Comment by homerjam** [comment]
Hi @mvnguyen83 

Could you create a plunkr/codepen example please?

I've tested the directive with ng-repeat successfully so I think it must be something else.

Thanks

James

**Comment by techno-mike-git** [comment]
Hi James,
Maybe I missing something but here's a [codepen](http://codepen.io/mvnguyen83/pen/GZwapV)

Thanks for looking at this,
Mike

**Comment by homerjam** [comment]
Cheers Mike,

So just to confirm - should the info panels tween towards the centre in a sort of cascading effect rather than simultaneously?

**Comment by techno-mike-git** [comment]
Yes, the panels move from outside to the center and it should trigger by each id of the panel but the "triggerElement" was not found. If you inspect the console you'll see the error.

**Comment by homerjam** [comment]
Mike, I think this should now be fixed. I'm not sure what the difference between my testing and your example was, possibly the compilation not happening fast enough in the ng-repeat. Anyway I've added a delay to counter this. I'd appreciate if you could confirm and re-open this issue if needed.

Cheers,
James

**Comment by homerjam** [comment]
Also would like to see this directive in the wild when you're finished!

**Comment by techno-mike-git** [comment]
Great! I'll update this and get back to you when if it works. Thanks James

**Comment by techno-mike-git** [comment]
Awesome! That works. Now I have to figure out if the scroll is on top or bottom, just initialize the tween without a trigger. Any advice will be helpful. Thanks

**Comment by homerjam** [comment]
I'm not sure quite what you mean? The tweens should be bound to the scroll position regardless. You could trigger the tweens 'manually' but as soon as the scroll event occurs again they will be overridden.

**Comment by techno-mike-git** [comment]
For [example](http://codepen.io/mvnguyen83/pen/GZwapV), the first panel doesn't need to be trigger tween with scroll. It just needs to move be to the center when on load. And when you scroll to the bottom, the last panel should just complete the tween without the trigger. I guess it should complete the tween when it detects the scroll is on the bottom since it can't reach the trigger element. Maybe $last with ng-repeat.

**Comment by homerjam** [comment]
Yes exactly use `ng-if="$first"`, `ng-if="$last"` and `ng-if="!$first && !$last"` to give different behaviours/triggers..

**Comment by techno-mike-git** [comment]
Or adjust the offset and duration when it's determined that the panels are on the bottom of the page. The `$last` wouldn't be that flexible since the second to the last panel is at the bottom too.
