### ISSUE TITLE
Easing

### ISSUE THREAD

**Issue by utiq** [homerjam/angular-scroll-magic#7]
How can I add easing to the "to-vars"? for example: {x:-24000,ease:SteppedEase.config(24)}

**Comment by homerjam** [comment]
Have you tried defining the vars in your controller?

**Comment by utiq** [comment]
It worked!, thanks!
I added:
`$scope.steppedEase = SteppedEase.config(24)`
in the controller, and:
`"to-vars" = "{'x': -24000, 'ease': steppedEase}"`
in the view
