### ISSUE TITLE
Consuming Service

### ISSUE THREAD

**Issue by utiq** [homerjam/angular-scroll-magic#8]
Hi, I have my code like this in the view and controller, but I receive _undefined_ for **scene**

```
<div sm-scene="scene-01"></div>
var scene = ScrollMagicService.getScene('scene-01');
console.log(scene)
```

Am I doing something wrong?

**Comment by homerjam** [comment]
Hi,

The scenes are probably being added after the controller is initialised, you should use the following method to access the scene as soon as its available:

```
ScrollMagicService.onSceneAdded('scene-01', function(scene) {
    // do stuff with `scene`
});
```

I'll add this to the docs!
